### ISSUE TITLE
Updating the site by pushing to GitHub

### ISSUE THREAD

**Issue by ninest** [HavenOfExcellence/mtrac-guide#2]
Before we ORD, we'll need to find a way to allow non-technical users to update the site. We cannot expect them to download the code, build the site, and push, so we could use a few GitHub actions perhaps:

```yaml
name: CD
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build site
        run: |
          npm install -g yarn
          yarn install --frozen-lockfile
          npm run build

      - name: Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Build site"
          git push
```
